<a href="https://colab.research.google.com/github/widhi19520008/UJSP-/blob/main/Pelatihan_Widhi_ujsp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2 + 3 + 9

14

In [ ]:
99 - 73

26

In [ ]:
23.54 * -1432

-33709.28

In [ ]:
100 / 7

14.285714285714286

In [ ]:
100 // 7

14

In [ ]:
100 % 7

2

In [ ]:
5 ** 3

125

In [ ]:
((2 + 5) * (17 - 3)) / (4 ** 3)

1.53125

In [ ]:
my_favorite_number = 1
my_least_favorite_number = 5
a_neutral_number = 3

In [ ]:
my_favorite_number == 1

True

In [ ]:
my_favorite_number == my_least_favorite_number

False

In [ ]:
my_favorite_number != a_neutral_number

True

In [ ]:
a_neutral_number != 3

False

In [ ]:
my_least_favorite_number > a_neutral_number

True

In [ ]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                        [-1.5, 2.4, 3.5],
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [ ]:
sample_data.shape

(4, 3)

In [ ]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [ ]:
preprocessor_scall = preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor_scall.fit(sample_data)

#cara 1
scaled_data = preprocessor_scall.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [ ]:
scaled_data = preprocessor_scall.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [ ]:
l1_normalized_data = preprocessing.normalize(sample_data, norm='l1' )
l1_normalized_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

In [ ]:
l1_normalized_data2 = preprocessing.normalize(sample_data, norm='l1' )
l1_normalized_data2

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

In [ ]:
label_kategori_hari = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu']
label_kategori_bulan = ['januari', 'februari', 'maret', 'april', 'mei', 'juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember']
encoder = preprocessing.LabelEncoder()
encoder.fit(label_kategori_bulan)

print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '=', i)


Label mapping:
agustus = 0
april = 1
desember = 2
februari = 3
januari = 4
juli = 5
juni = 6
maret = 7
mei = 8
november = 9
oktober = 10
september = 11
