<a href="https://colab.research.google.com/github/widhi19520008/UJSP-/blob/main/WIDHI_19_52_0008___TUGAS_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+3+9

14

In [ ]:
99-73

26

In [ ]:
23.54*-1432

-33709.28

In [ ]:
100/7

14.285714285714286

In [ ]:
100//7

14

In [ ]:
100%7

2

In [ ]:
5**3

125

In [ ]:
((2+5)*(17-3))/(4**3)

1.53125

In [ ]:
my_favorit_number = 1
my_least_favorit_number = 5
a_neutral_number = 3

In [ ]:
# Equality check - True
my_favorit_number == 1

True

In [ ]:
# Equality check -False
my_favorit_number == my_least_favorit_number

False

In [ ]:
# Not equal check - True
my_least_favorit_number != a_neutral_number

True

In [ ]:
# Not equal chek - False
a_neutral_number != 3

False

In [ ]:
# Greater than check - True
my_least_favorit_number > a_neutral_number

True

In [ ]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                       [-1.5, 2.4, 3.5],
                       [0.5, -7.9, 5.6],
                       [5.9, 2.3, -5.8]])
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [ ]:
sample_data.shape

(4, 3)

In [ ]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [ ]:
preprocessor = preprocessing.Binarizer(threshold=0.2)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

Teknik Scalling

In [ ]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [ ]:
preprocessor_scall = preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor_scall.fit(sample_data)

#cara 1
scaled_data = preprocessor_scall.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [ ]:
#cara 2
scaled_data = preprocessor_scall.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Teknik Normalization L1

In [ ]:
# normalized l1
l1_normalized_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalized_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

In [ ]:
# normalized l2
l1_normalized_data = preprocessing.normalize(sample_data, norm='l2')
l1_normalized_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

In [ ]:
# Encoding
label_kategori_hari =['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu']
label_kategori_bulan =['januari', 'februari', 'maret']
encoder = preprocessing.LabelEncoder()
encoder.fit(label_kategori_bulan)

print ("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
  print (item, '=', i)


Label mapping:
februari = 0
januari = 1
maret = 2
